const SEVERITY_LEVELS = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical'
};

const SEVERITY_OPTIONS = [
  SEVERITY_LEVELS.LOW,
  SEVERITY_LEVELS.MEDIUM,
  SEVERITY_LEVELS.HIGH,
  SEVERITY_LEVELS.CRITICAL
];

module.exports = {
  SEVERITY_LEVELS,
  SEVERITY_OPTIONS
};
